package com.mhframework;

import android.app.Activity;
import android.os.Bundle;

/********************************************************************
 * Auto generated by Eclipse.
 */
public class MainActivity extends Activity {

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
	}

}
